### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by nugmanoff** [QuickBirdEng/XCoordinator#230]
Hi guys!

Thank you for an amazing library. I've just discovered it after 2 years of doing Coordinators from scratch myself in every project. I was just exploring the project and while reading the README stumbled upon the [documentation link](https://quickbirdstudios.github.io/XCoordinator) that appears to be broken.

Is just the link is broken and there is an additional documentation apart from README? Or is all documentation available is README?

Thanks!

**Comment by pauljohanneskraft** [comment]
Hey @nugmanoff - Thank you very much for letting us know! You can find the documentation [here](https://quickbirdeng.github.io/XCoordinator/).
