### ISSUE TITLE
Logging of triggered Routes

### ISSUE THREAD

**Issue by cornr** [QuickBirdEng/XCoordinator#231]
Hi and thanks for this awesome library.

We are using several Coordinators in our App. Now we would like to log which route has been triggered.
We could implement this in each `Coordinator` implementation in `prepareTransition(for route:)`. But this could easily be forgotten.
Is there a way to hook into the `Coordinator` or some other place to generically print each triggered `Route` to the console?

Thanks for any help.
Jonas

**Comment by pauljohanneskraft** [comment]
Hey @cornr - thank you for your interest in this library. 

Unfortunately, there is no such functionality at the moment. You might however be possible to create your own subclasses to NavigationCoordinator, TabBarCoordinator, etc with that logging functionality to at least reduce code duplication.
