### ISSUE TITLE
Route with Generics

### ISSUE THREAD

**Issue by fraserscottmorrison** [QuickBirdEng/XCoordinator#234]
Hi I have been integrating your library with my project and loving it so far. Your support for deep links is brilliant too.

Ive encountered a stumbling block on one of my screens that has a list of generic items that get displayed in a menu of cards/tiles and each can transition to their own view which Id like to have their own Route/Coordinator (each coordinator and its screen will be in their own SPM Package)

Because the cards list is generic it can have any number of conforming items and so their routes cannot be explicitly defined in CardsMenuRoute

Ive tried using generics in the CardsMenuRoute such as below, but Im getting errors here. Perhaps Im struggling as my Swift 5.7 generics isn't up to scratch. But perhaps you know the right way to solve this, or a better way?

```
enum CardsMenuRoute: Route {
    case menuDetail(StrongRouter<any Route>)
}

override func prepareTransition(for route: CardsMenuRoute) -> NavigationTransition {
        switch route {
        case .widget(let cardsMenuRoute):
            return .push(cardsMenuRoute)
        }
    }
```
Cheers

**Comment by pauljohanneskraft** [comment]
Hey - thank you for your kind words. Would it work to use `any Presentable` here instead of `StrongRouter<any Route>`?

**Comment by fraserscottmorrison** [comment]
Cheers for the quick reply. `StrongRouter` and `UnownedRouter` both require a `Route`.

In Swift 5.7 protocols must now provide an existential type. And the proper say to provide any Route would be to use type erasure. So I'll have a go at creating an AnyRoute class, later this week.

**Comment by pauljohanneskraft** [comment]
I know that, but you are not actually using the router's functionality anywhere in the example you provided, so it might simply be easier to go one step higher in the inheritance and simply make the associated object of that case a `Presentable`, since that's what is required by `Transition.push`. Or do you need more information about the router than what is part of your example?

What I'm proposing is:

```swift
enum CardsMenuRoute: Route {
    case menuDetail(any Presentable)
}

override func prepareTransition(for route: CardsMenuRoute) -> NavigationTransition {
        switch route {
        case .widget(let cardsMenuRoute):
            return .push(cardsMenuRoute)
        }
    }
```

**Comment by fraserscottmorrison** [comment]
Hi again. Thanks for your suggestion. 

In `prepareTransition` I need add a child coordinator (which is located in a SPM dependency) and `.trigger` one of its routes, generically.

I adapted your suggestion a little and think Im pretty close. Instead of passing in an any Presentable I pass trough a Transition.

```enum CardsMenuRoute: Route {
    case menuDetail(Transition<UINavigationController>)
}
override func prepareTransition(for route: CardsMenuRoute) -> NavigationTransition {
        switch route {
        case .menuDetail(let transition):
            return transition
        }
    }```

The transition can then be created in the SPM dependency and passed up to the CardsCoordinator via a trigger. The stumbling bock is now that the SPM Dependency Coordinator initialiser needs the CardsCoordinator to set its rootViewController.

I haven't found a way to pass the CardsCoordinator into the SPM Dependency because NavigationCoordinator is generic so the dependency needs to know the concrete type of Route (CardsMenuRoute, which it doesn't know about)

I hope Ive explained this, without confusing things. Id really appreciate any other ideas you have here
Cheers
Fraser

**Comment by fraserscottmorrison** [comment]
Hi again, I hope I was able to explain the situation clearly. Also I haven't missed anything obvious have I?

If you'd need me to provide more code, or an example project, I could help. 

This is the only thing holding me back from adopting XCoordinator, so I'd love to get a solution to this issue

Cheers again
Fraser

**Comment by fraserscottmorrison** [comment]
Hi I now have a solution for generically adding coordinators. Just needed a break from it - turned out not to tricky.

Here's the rough solution I used. The modules array can have any number of modules which need to adhere to the UICardProtocol which defines a method for .getCardsView
`

    lazy var modules: [any UICardProtocol] = [Accounts.module(), Menu.module()]

    init(router: UnownedRouter<LandingRoute>, coordinator: NavigationCoordinator<MainRoute>) {
        self.router = router

        let cards = self.modules.flatMap { $0.getCardsView(rootCoordinator: coordinator)}
    }

    static func getCardsView<R>(rootCoordinator: NavigationCoordinator<R>) -> [CardsView] where R: Route {
        let cardsCoordinator = CardsCoordinator(rootViewController: rootCoordinator.rootViewController)
        rootCoordinator.addChild(cardsCoordinator)

        let viewModel = CardsViewModel(router: cardsCoordinator.unownedRouter)
        return CardsView(viewModel: viewModel)
    }`

**Comment by fraserscottmorrison** [comment]
Closing as now resolved
